services:
  arch-wine-fs25:
    image: philipulrich/arch-wine-fs25:latest
    container_name: arch-wine-fs25
    environment:
      - VNC_PASSWORD=<your vnc password>
      - PUID=<UID from user>
      - PGID=<UID from user>
      - WEB_USERNAME=<dedicated server portal username>
      - WEB_PASSWORD=<dedicated server portal password>
      - SERVER_NAME=<your server name>
      - SERVER_PASSWORD=<your game join password>
      - SERVER_ADMIN=<your server admin password>
      - SERVER_PLAYERS=12
      - SERVER_PORT=10823
      - SERVER_REGION=en
      - SERVER_DIFFICULTY=3
      - SERVER_PAUSE=1
      - SERVER_SAVE_INTERVAL=15.000000
      - SERVER_STATS_INTERVAL=60.000000
      - SERVER_CROSSPLAY=false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/fs25/config:/opt/fs25/config
      - /opt/fs25/game:/opt/fs25/game
      - /opt/fs25/dlc:/opt/fs25/dlc
      - /opt/fs25/installer:/opt/fs25/installer
    ports:
      - 5900:5900/tcp
      - 8080:8080/tcp
      - 10823:10823/tcp
      - 10823:10823/udp
    cap_add:
      - SYS_NICE
    restart: unless-stopped
